import { Article } from './types';

export const articles: Article[] = [
  {
    id: '1',
    slug: 'climate-summit-agreement',
    title: 'Global Climate Summit Reaches Historic Agreement',
    excerpt: 'Nations unite on climate action with binding commitments to reduce emissions by 2030.',
    content: 'In a landmark development, world leaders have reached a comprehensive agreement at the Global Climate Summit. The accord commits nations to reduce carbon emissions by at least 45% by 2030 and includes a $100 billion climate fund for developing nations. This represents the most ambitious climate agreement since the Paris Accord. Scientists have praised the deal, though environmental groups say more aggressive action is needed. The agreement will take effect on January 1st next year.',
    category: 'world',
    author: 'Sarah Mitchell',
    date: '2024-03-25',
    image: '/images/climate.jpg',
    views: 15420,
  },
  {
    id: '2',
    slug: 'uk-economy-growth',
    title: 'UK Economy Shows Strong Growth in Latest Quarter',
    excerpt: 'The British economy expands faster than forecasts, boosting confidence in the market.',
    content: 'The UK economy grew by 0.8% in the fourth quarter, significantly outperforming economist predictions of 0.5%. This growth has been driven by strong performance in the service sector and manufacturing. The Office for National Statistics reports that consumer spending increased by 1.2%, suggesting improved consumer confidence. Retail sales surged following the early spring season. However, inflation remains a concern with the Bank of England maintaining rates at 5.0%.',
    category: 'uk',
    author: 'James Thompson',
    date: '2024-03-24',
    image: '/images/uk-economy.jpg',
    views: 12300,
  },
  {
    id: '3',
    slug: 'tech-breakthrough-ai',
    title: 'Major Breakthrough in Artificial Intelligence Research',
    excerpt: 'Scientists announce significant advancement in AI efficiency and safety mechanisms.',
    content: 'Researchers have made a substantial breakthrough in AI technology, developing a new algorithm that increases processing efficiency by 300% while reducing energy consumption. The advancement addresses one of the major concerns in AI development: the environmental impact of training large models. The new approach uses novel neural network architecture that mimics biological brain functions more closely. Leading tech companies have already expressed interest in implementing the technology. The breakthrough was announced at the International AI Conference and is considered a game-changer for the industry.',
    category: 'tech',
    author: 'Dr. Emma Chen',
    date: '2024-03-23',
    image: '/images/ai.jpg',
    views: 18900,
  },
  {
    id: '4',
    slug: 'quantum-computing-leap',
    title: 'Quantum Computer Achieves New Milestone',
    excerpt: 'Scientists demonstrate quantum computing capability previously thought impossible.',
    content: 'A team of physicists has successfully demonstrated quantum error correction at scale, a breakthrough that brings practical quantum computers closer to reality. The achievement solves a critical problem that has plagued quantum computing: the instability of quantum bits. The new method maintains quantum information with 99.9% accuracy across multiple operations. This opens new possibilities for solving complex problems in drug development, materials science, and cryptography. Industry experts believe this could lead to practical quantum computers within the next five years.',
    category: 'science',
    author: 'Prof. Richard Adams',
    date: '2024-03-22',
    image: '/images/quantum.jpg',
    views: 11200,
  },
  {
    id: '5',
    slug: 'tech-giant-acquisition',
    title: 'Tech Giant Announces $50 Billion Acquisition',
    excerpt: 'Major technology company completes landmark acquisition in strategic expansion.',
    content: 'One of the world\'s largest technology companies has announced the acquisition of a leading software firm for $50 billion. The deal, approved by regulators after a six-month review, is expected to create significant synergies in cloud computing and AI. The acquisition brings together complementary technologies and talent pools. Market analysts predict the combined entity will have even greater market dominance. The integration is expected to complete by the end of the year.',
    category: 'business',
    author: 'Michael Reuters',
    date: '2024-03-21',
    image: '/images/tech-deal.jpg',
    views: 9800,
  },
  {
    id: '6',
    slug: 'new-cancer-treatment',
    title: 'Breakthrough in Cancer Treatment Shows Promise',
    excerpt: 'New immunotherapy approach shows 85% success rate in clinical trials.',
    content: 'Medical researchers have announced successful results from clinical trials of a new cancer immunotherapy. The treatment showed an 85% positive response rate in patients with advanced melanoma. The therapy works by enhancing the body\'s own immune system to fight cancer cells more effectively. Patients in the trial experienced fewer side effects compared to traditional chemotherapy. The treatment is expected to be reviewed for approval within the next year.',
    category: 'health',
    author: 'Dr. Lisa Johnson',
    date: '2024-03-20',
    image: '/images/health.jpg',
    views: 14600,
  },
  {
    id: '7',
    slug: 'world-cup-upset',
    title: 'Underdog Team Reaches World Cup Final',
    excerpt: 'Historic achievement as unexpected contender defeats defending champions.',
    content: 'In a shocking upset, an underdog team has defeated the defending world champions to secure a place in the finals. The victory, achieved through a dramatic penalty shootout, has captivated global audiences. The team\'s remarkable journey from preliminary rounds to the final represents one of the greatest sports stories in recent history. Coach praised the team\'s determination and tactical brilliance. The final is scheduled for next month.',
    category: 'sport',
    author: 'David Foster',
    date: '2024-03-19',
    image: '/images/sports.jpg',
    views: 22100,
  },
  {
    id: '8',
    slug: 'business-merger',
    title: 'Major Banking Merger Approved by Regulators',
    excerpt: 'Two financial institutions combine to create industry powerhouse.',
    content: 'Banking regulators have approved the merger of two major financial institutions, creating a combined entity with over $2 trillion in assets. The merger is expected to generate cost savings and create a more competitive global player. Both institutions\' customers will benefit from expanded services and geographic reach. The integration process is expected to take 18 months. Leadership teams from both banks will oversee the transition.',
    category: 'business',
    author: 'Catherine Wells',
    date: '2024-03-18',
    image: '/images/finance.jpg',
    views: 8400,
  },
  {
    id: '9',
    slug: 'space-exploration',
    title: 'Historic Mars Mission Reaches Critical Milestone',
    excerpt: 'Space agency successfully deploys advanced rover on Mars surface.',
    content: 'Space exploration reached a new milestone as a cutting-edge rover successfully deployed on Mars. The rover is equipped with advanced instruments to search for signs of ancient microbial life. Initial transmissions show all systems functioning perfectly. The mission represents years of planning and collaboration between multiple space agencies. Data from this mission will inform future crewed missions to Mars.',
    category: 'science',
    author: 'Prof. Alexandra Brown',
    date: '2024-03-17',
    image: '/images/space.jpg',
    views: 16700,
  },
  {
    id: '10',
    slug: 'smartphone-innovation',
    title: 'New Smartphone Technology Revolutionizes Industry',
    excerpt: 'Innovative display technology delivers unprecedented performance and efficiency.',
    content: 'A major smartphone manufacturer has unveiled revolutionary display technology that pushes the boundaries of mobile computing. The new holographic display offers 4K resolution with zero bezel and offers 5000 nits of brightness. Battery life extends to 7 days on a single charge thanks to new power management. The technology also enables gesture recognition without physical contact. Pre-orders exceed 5 million units within the first 24 hours.',
    category: 'tech',
    author: 'Marcus Lee',
    date: '2024-03-16',
    image: '/images/tech-phone.jpg',
    views: 19300,
  },
  {
    id: '11',
    slug: 'election-results-analysis',
    title: 'Election Results Show Major Political Shift',
    excerpt: 'Voters deliver surprising mandate in historic election outcome.',
    content: 'Recent election results have sent shockwaves through the political establishment. The unexpected voter mandate represents a significant shift in political dynamics. Analysts are examining the implications for policy and governance. Key issues including economy, healthcare, and climate were decisive factors.',
    category: 'world',
    author: 'John Mitchell',
    date: '2024-03-25',
    image: '/images/climate.jpg',
    views: 20100,
  },
  {
    id: '12',
    slug: 'trade-agreement-signed',
    title: 'Major Trade Agreement Signed Between Nations',
    excerpt: 'Historic trade deal opens new markets and creates opportunities.',
    content: 'Two major economies have finalized a comprehensive trade agreement expected to boost bilateral commerce by 35%. The deal eliminates tariffs on key sectors and creates new investment opportunities.',
    category: 'business',
    author: 'Robert Chen',
    date: '2024-03-24',
    image: '/images/finance.jpg',
    views: 7200,
  },
  {
    id: '13',
    slug: 'renewable-energy-surge',
    title: 'Renewable Energy Usage Reaches Record Levels',
    excerpt: 'Solar and wind power now account for largest share of energy production.',
    content: 'Global renewable energy capacity has surpassed expectations, now accounting for 42% of worldwide electricity generation. Wind and solar installations continue to accelerate across continents.',
    category: 'world',
    author: 'Emma Green',
    date: '2024-03-23',
    image: '/images/climate.jpg',
    views: 13400,
  },
  {
    id: '14',
    slug: 'wildlife-conservation-victory',
    title: 'Endangered Species Population Recovers',
    excerpt: 'Conservation efforts lead to remarkable turnaround for critically endangered animals.',
    content: 'After decades of decline, populations of a critically endangered species have rebounded significantly. International conservation efforts and habitat protection have proven successful.',
    category: 'world',
    author: 'Sarah Wilson',
    date: '2024-03-22',
    image: '/images/climate.jpg',
    views: 11800,
  },
  {
    id: '15',
    slug: 'innovation-startups-boom',
    title: 'Tech Startups Secure Record Funding Rounds',
    excerpt: 'Venture capital flows as investors bet on emerging technologies.',
    content: 'Technology startups have attracted unprecedented venture capital investment this quarter. Investors are particularly focused on AI, biotech, and green energy companies.',
    category: 'tech',
    author: 'David Park',
    date: '2024-03-21',
    image: '/images/ai.jpg',
    views: 9500,
  },
  {
    id: '16',
    slug: 'pharmaceutical-discovery',
    title: 'New Drug Shows Potential for Alzheimers Treatment',
    excerpt: 'Clinical trials demonstrate promising results in neurological disease research.',
    content: 'Pharmaceutical researchers have unveiled a new compound that shows remarkable promise in treating Alzheimers disease. Early trials show slowing of cognitive decline in patients.',
    category: 'health',
    author: 'Dr. Michael Brown',
    date: '2024-03-20',
    image: '/images/health.jpg',
    views: 15200,
  },
  {
    id: '17',
    slug: 'olympics-preparation',
    title: 'Olympic Games Preparations Enter Final Phase',
    excerpt: 'Host nation completes major venue construction ahead of summer games.',
    content: 'Construction of Olympic venues is nearing completion as the host nation prepares for the upcoming summer games. Athletes from around the world are beginning training camps.',
    category: 'sport',
    author: 'Tommy Anderson',
    date: '2024-03-19',
    image: '/images/sports.jpg',
    views: 12600,
  },
  {
    id: '18',
    slug: 'cultural-festival-success',
    title: 'International Film Festival Draws Record Attendance',
    excerpt: 'Cinematic celebration showcases films from 100+ countries.',
    content: 'The worlds largest international film festival has concluded with record-breaking attendance figures. Film enthusiasts from across the globe celebrated cinema across multiple venues.',
    category: 'world',
    author: 'Isabella Marco',
    date: '2024-03-18',
    image: '/images/climate.jpg',
    views: 8700,
  },
  {
    id: '19',
    slug: 'inflation-data-mixed',
    title: 'Latest Inflation Data Shows Mixed Signals',
    excerpt: 'Economic indicators provide confusing picture of price pressures.',
    content: 'The latest inflation statistics reveal complex economic dynamics. While some sectors show cooling prices, others continue rising. Economists debate the implications for monetary policy.',
    category: 'business',
    author: 'Kevin Harrison',
    date: '2024-03-17',
    image: '/images/finance.jpg',
    views: 6800,
  },
  {
    id: '20',
    slug: 'earthquake-response',
    title: 'International Aid Mobilizes After Major Earthquake',
    excerpt: 'Global response to natural disaster demonstrates cooperation and compassion.',
    content: 'Following a significant earthquake, international organizations have mobilized resources to support affected regions. Search and rescue operations continue around the clock.',
    category: 'world',
    author: 'Alex Rodriguez',
    date: '2024-03-16',
    image: '/images/climate.jpg',
    views: 18900,
  },
  {
    id: '21',
    slug: 'sports-transfer-news',
    title: 'Record-Breaking Sports Transfer Shocks Industry',
    excerpt: 'Athlete signs multi-year mega-deal with major franchise.',
    content: 'In a stunning transfer, a superstar athlete has signed with a major sports franchise for an unprecedented salary. The deal breaks all previous records in professional sports.',
    category: 'sport',
    author: 'Mark Stevens',
    date: '2024-03-15',
    image: '/images/sports.jpg',
    views: 21300,
  },
  {
    id: '22',
    slug: 'education-innovation',
    title: 'New Education Model Shows Dramatic Results',
    excerpt: 'Student achievement reaches all-time highs under innovative teaching methods.',
    content: 'Schools implementing a revolutionary education approach are seeing unprecedented student achievement levels. The method combines traditional learning with modern technology.',
    category: 'world',
    author: 'Professor Lisa Chan',
    date: '2024-03-14',
    image: '/images/climate.jpg',
    views: 10200,
  },
  {
    id: '23',
    slug: 'cybersecurity-threat',
    title: 'Major Cybersecurity Breach Affects Millions',
    excerpt: 'Data leak raises concerns about online privacy and security.',
    content: 'A significant cybersecurity breach has exposed personal data of millions of users. Companies are implementing enhanced security measures in response.',
    category: 'tech',
    author: 'Steven Murphy',
    date: '2024-03-13',
    image: '/images/ai.jpg',
    views: 16700,
  },
  {
    id: '24',
    slug: 'agricultural-breakthrough',
    title: 'New Crop Variety Yields Double Production',
    excerpt: 'Agricultural innovation promises to address food security concerns.',
    content: 'Scientists have developed a new crop variety that doubles conventional yields while using fewer resources. The breakthrough could revolutionize global food production.',
    category: 'science',
    author: 'Dr. Rachel White',
    date: '2024-03-12',
    image: '/images/quantum.jpg',
    views: 9400,
  },
  {
    id: '25',
    slug: 'ocean-exploration',
    title: 'Deep Ocean Expedition Discovers New Species',
    excerpt: 'Marine research reveals unexpected biodiversity in abyssal zones.',
    content: 'An expedition to the deepest ocean trenches has discovered dozens of previously unknown species. The findings could change our understanding of marine ecosystems.',
    category: 'science',
    author: 'Prof. James Harbor',
    date: '2024-03-11',
    image: '/images/space.jpg',
    views: 14100,
  },
  {
    id: '26',
    slug: 'blockbuster-film-record',
    title: 'New Blockbuster Shatters Opening Weekend Box Office Record',
    excerpt: 'The highly anticipated sequel breaks all previous records with a $500 million global debut.',
    content: 'The latest installment in one of cinema\'s biggest franchises has obliterated opening weekend records worldwide. The film earned $500 million globally in its first three days, surpassing the previous record by $80 million. Critics and audiences alike have praised the film for its stunning visuals and compelling story. The director credited an enormous cast and crew for bringing the vision to life. Streaming rights are expected to be negotiated following the theatrical run.',
    category: 'entertainment',
    author: 'Sophie Clarke',
    date: '2024-03-25',
    image: '/images/sports.jpg',
    views: 25300,
  },
  {
    id: '27',
    slug: 'music-award-ceremony',
    title: 'Global Music Awards Celebrate Breakthrough Artists',
    excerpt: 'Annual ceremony honors the biggest names and rising stars of the music industry.',
    content: 'The Global Music Awards ceremony delivered thrilling performances and surprising wins. Emerging artists dominated multiple categories, signalling a significant shift in the music industry. The event, watched by over 50 million viewers worldwide, highlighted diversity and innovation. Several nominees made history as the first from their genre to receive nominations. Industry executives predict record-breaking album sales following the exposure.',
    category: 'entertainment',
    author: 'Marcus Gold',
    date: '2024-03-23',
    image: '/images/health.jpg',
    views: 18700,
  },
  {
    id: '28',
    slug: 'streaming-war-heats-up',
    title: 'Streaming Giants Battle for Subscribers with Exclusive Content',
    excerpt: 'Major platforms announce billion-dollar investments in original programming to win audiences.',
    content: 'The streaming wars have intensified with multiple platforms announcing major original content investments. Billions of dollars are being committed to exclusive series and films. Subscriber numbers are the key battleground as platforms compete for audience share. Analysts predict further consolidation in the streaming market within the next two years. Consumer choice has never been greater but decision fatigue is a growing concern.',
    category: 'entertainment',
    author: 'Diana Reeves',
    date: '2024-03-21',
    image: '/images/tech-deal.jpg',
    views: 14200,
  },
  {
    id: '29',
    slug: 'local-infrastructure-project',
    title: 'City Council Approves Major Infrastructure Upgrade',
    excerpt: 'Landmark investment in roads, public transport and green spaces to transform city centre.',
    content: 'The city council has approved a comprehensive infrastructure upgrade worth $2 billion. The project covers road improvements, new bus rapid transit routes, and the creation of three new public parks. Construction is expected to begin next quarter and complete within four years. Residents have welcomed the investment, particularly the improved cycling and pedestrian infrastructure. Local businesses anticipate increased foot traffic following the upgrades.',
    category: 'local-news',
    author: 'Helen Morris',
    date: '2024-03-24',
    image: '/images/uk-economy.jpg',
    views: 8900,
  },
  {
    id: '30',
    slug: 'community-school-expansion',
    title: 'Community School Opens New Facilities After Fundraising Drive',
    excerpt: 'Local school celebrates opening of state-of-the-art science labs and sports hall.',
    content: 'A local school celebrated the opening of new science laboratories and a modern sports hall following a successful community fundraising campaign. Over $1.2 million was raised through donations from parents, local businesses, and council grants. Students and teachers are excited to use the new facilities. The head teacher praised the community spirit that made the project possible. The new facilities are also available for community use during evenings and weekends.',
    category: 'local-news',
    author: 'Daniel Foster',
    date: '2024-03-22',
    image: '/images/health.jpg',
    views: 6400,
  },
  {
    id: '31',
    slug: 'local-market-expansion',
    title: 'Local Farmers Market Expands to New Weekend Venue',
    excerpt: 'Popular market doubles in size after overwhelming demand from vendors and shoppers.',
    content: 'The popular local farmers market is expanding to a second weekly venue following overwhelming demand. Over 80 new vendors have been approved to join the market, offering everything from artisan foods to handmade crafts. Organisers expect the expansion to create over 200 local jobs. The market has become a key community hub, attracting thousands of visitors each weekend. Plans are in place to introduce live music and cooking demonstrations.',
    category: 'local-news',
    author: 'Anna Blake',
    date: '2024-03-20',
    image: '/images/finance.jpg',
    views: 5200,
  },
  {
    id: '32',
    slug: 'local-hospital-new-wing',
    title: 'New Hospital Wing Cuts Patient Waiting Times by 40%',
    excerpt: 'Expanded emergency department now handles twice the capacity with improved care.',
    content: 'The regional hospital has opened its new emergency department wing, already delivering a 40% reduction in average patient waiting times. The expansion adds 60 new beds, two additional operating theatres and a dedicated paediatric unit. Medical staff said the new facilities have transformed patient care quality. Government funding and private donations made the £25 million project possible. The hospital CEO described it as the most significant improvement in local healthcare in a generation.',
    category: 'local-news',
    author: 'Carol Simmons',
    date: '2024-03-18',
    image: '/images/health.jpg',
    views: 9700,
  },
];

export function getArticleBySlug(slug: string): Article | undefined {
  return articles.find((article) => article.slug === slug);
}

export function getArticlesByCategory(category: string): Article[] {
  return articles.filter((article) => article.category === category);
}

export function getFeaturedArticle(): Article {
  return articles[0];
}

export function getTrendingArticles(limit: number = 5): Article[] {
  return [...articles].sort((a, b) => b.views - a.views).slice(0, limit);
}
